### ISSUE TITLE
Error inesperado al introducir una "variable no asignada"

### ISSUE THREAD

**Issue by gcrespi** [gobstones/PyGobstones-Lang#15]
Antes del commit 7037e49 el programa:
program {
        Poner(a)
}

Mostraba la siguiente advertencia:

<pre>
--
sarasa.gbs (línea 2, columna 15)
cerca de un identificador con minúscula "a"
              |
              V
        Poner(a)

--

Advertencia en el uso de las variables:

    La variable "a" podría no tener asignado ningún valor
    en este punto del programa
</pre>

Ahora tira el siguiente error

<pre>
Traceback (most recent call last):
  File "pygobstoneslang.py", line 6, in <module>
    main()
  File "/home/foo/PyGobstones-Lang/pygobstoneslang/__main__.py", line 351, in main
    report_program_error(exception.error_type(), exception.msg, exception.area)
  File "/home/foo/PyGobstones-Lang/pygobstoneslang/__main__.py", line 45, in report_program_error
    LOGGER.error('\n%s\n' % (area,))
  File "/home/foo/PyGobstones-Lang/pygobstoneslang/common/position.py", line 100, in __repr__
    i18n.i18n('near'), self.elem.description())
  File "/home/foo/PyGobstones-Lang/pygobstoneslang/lang/parser/Token.py", line 55, in description
    return repr(self)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfa' in position 24: ordinal not in range(128)
</pre>

**Comment by arypbatista** [comment]
Arreglado en último commit.
