### ISSUE TITLE
Return AST in JSON format

### ISSUE THREAD

**Issue by faloi** [gobstones/PyGobstones-Lang#3]
Because parsing JSON is almost free in any language.

**Comment by arypbatista** [comment]
Hola @faloi ,

Si actualizás a la última versión, podés acceder a esta funcionalidad a través del comando:

 ./gbs.py <gobstonesFile> --output-type json --print-ast --target parse

La opción "target" con valor "parse" hace que el interprete solo ejecute la fase de parseo y no avance en su pipeline. No está documentado esto... lo haré luego (quizás).

Saludos!

**Comment by arypbatista** [comment]
Ah, y podés parsear procedimientos, funciones y tipos sin tener un program definido. Pero no pedazos de código arbitrarios.

**Comment by faloi** [comment]
Buenísimo che, es todo lo que quería. Podríamos cerrar ambas issues.

Peeeero hay un problema: ponga el flag que ponga, siempre se rompe con este error:

```
Haciendo análisis sintáctico.
Explotando macros del programa.
Python Error: :

    Failed to execute /home/faloi/Desktop/gobstones/ast.gbs file.

ERROR:root:global name 'tree' is not defined
Traceback (most recent call last):
  File "./.heroku/vendor/pygobstones-lang/gbs.py", line 293, in main
    gbs_run = run_filename(options['src'], options)
  File "./.heroku/vendor/pygobstones-lang/gbs.py", line 270, in run_filename
    gbs_run = gobstones.run(filename, open(filename).read(), get_initial_board(options))
  File "/home/faloi/workspace/mumuki/stones-spec/.heroku/vendor/pygobstones-lang/lang/__init__.py", line 123, in run
    gbs_run = self.compile(filename, program_text)
  File "/home/faloi/workspace/mumuki/stones-spec/.heroku/vendor/pygobstones-lang/lang/__init__.py", line 103, in compile
    self.check(tree)
NameError: global name 'tree' is not defined
```

**Comment by arypbatista** [comment]
Colgué.. Eso por no correr los tests. Ahora subo el fix
