### ISSUE TITLE
Se rompió el mensaje de error "El programa está vacío"

### ISSUE THREAD

**Issue by faloi** [gobstones/PyGobstones-Lang#9]
Antes de que estuviera la opción `--target parse`, este era el output al compilar un programa vacio:

```
--
/home/faloi/Desktop/gobstones/vacio.gbs (línea 1, columna 1)
cerca de 
|
V

--

Error en el programa:

    El programa está vacío.

Traceback (most recent call last):
  File "/home/faloi/bin/gbs", line 265, in <module>
    main()
  File "/home/faloi/bin/gbs", line 260, in main
    assert False
AssertionError
```

Y ahora muestra esto:

```
Python Error: :

    Failed to execute /home/faloi/Desktop/gobstones/vacio.gbs file.

ERROR:root:
Traceback (most recent call last):
  File "./gbs.py", line 295, in main
    gbs_run = run_filename(options['src'], options)
  File "./gbs.py", line 272, in run_filename
    gbs_run = gobstones.run(filename, open(filename).read(), get_initial_board(options))
  File "/home/faloi/workspace/mumuki/gobstones-server/.heroku/vendor/pygobstones-lang/lang/__init__.py", line 123, in run
    gbs_run = self.compile(filename, program_text)
  File "/home/faloi/workspace/mumuki/gobstones-server/.heroku/vendor/pygobstones-lang/lang/__init__.py", line 100, in compile
    gbs_run = self.parse(filename, program_text)
  File "/home/faloi/workspace/mumuki/gobstones-server/.heroku/vendor/pygobstones-lang/lang/__init__.py", line 92, in parse
    tree = self._parse(program_text, filename)
  File "/home/faloi/workspace/mumuki/gobstones-server/.heroku/vendor/pygobstones-lang/lang/__init__.py", line 65, in _parse
    raise GobstonesException(i18n.i18n("Cannot execute an empty program"))
GobstonesException
```

**Comment by arypbatista** [comment]
Arreglado.
